BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Payments] ALTER COLUMN [Status] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[Payments] ALTER COLUMN [InvoiceUrl] NVARCHAR(max) NULL;
ALTER TABLE [dbo].[Payments] ALTER COLUMN [PaidAt] DATETIME NULL;
ALTER TABLE [dbo].[Payments] ALTER COLUMN [InvoiceId] NVARCHAR(50) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
