BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Jobs] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [UserId] INT NOT NULL,
    [JobName] NVARCHAR(1000) NOT NULL,
    [Period] INT NOT NULL,
    [Config] NVARCHAR(1000) NOT NULL,
    [IsActive] NVARCHAR(1000) NOT NULL,
    [NextRun] DATETIME2 NOT NULL,
    CONSTRAINT [Jobs_pkey] PRIMARY KEY CLUSTERED ([Id])
);

-- AddForeignKey
ALTER TABLE [dbo].[Jobs] ADD CONSTRAINT [Jobs_UserId_fkey] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
